Collections:
  - Name: NAS-FCOS
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 4x V100 GPUs
      Architecture:
        - FPN
        - NAS-FCOS
        - ResNet
    Paper:
      URL: https://arxiv.org/abs/1906.04423
      Title: 'NAS-FCOS: Fast Neural Architecture Search for Object Detection'
    README: configs/nas_fcos/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.1.0/mmdet/models/detectors/nasfcos.py#L6
      Version: v2.1.0

Models:
  - Name: nas-fcos_r50-caffe_fpn_nashead-gn-head_4xb4-1x_coco
    In Collection: NAS-FCOS
    Config: configs/nas_fcos/nas-fcos_r50-caffe_fpn_nashead-gn-head_4xb4-1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/nas_fcos/nas_fcos_nashead_r50_caffe_fpn_gn-head_4x4_1x_coco/nas_fcos_nashead_r50_caffe_fpn_gn-head_4x4_1x_coco_20200520-1bdba3ce.pth

  - Name: nas-fcos_r50-caffe_fpn_fcoshead-gn-head_4xb4-1x_coco
    In Collection: NAS-FCOS
    Config: configs/nas_fcos/nas-fcos_r50-caffe_fpn_fcoshead-gn-head_4xb4-1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/nas_fcos/nas_fcos_fcoshead_r50_caffe_fpn_gn-head_4x4_1x_coco/nas_fcos_fcoshead_r50_caffe_fpn_gn-head_4x4_1x_coco_20200521-7fdcbce0.pth
