Collections:
  - Name: TridentNet
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - ResNet
        - TridentNet Block
    Paper:
      URL: https://arxiv.org/abs/1901.01892
      Title: 'Scale-Aware Trident Networks for Object Detection'
    README: configs/tridentnet/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.8.0/mmdet/models/detectors/trident_faster_rcnn.py#L6
      Version: v2.8.0

Models:
  - Name: tridentnet_r50-caffe_1x_coco
    In Collection: TridentNet
    Config: configs/tridentnet/tridentnet_r50-caffe_1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.7
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tridentnet/tridentnet_r50_caffe_1x_coco/tridentnet_r50_caffe_1x_coco_20201230_141838-2ec0b530.pth

  - Name: tridentnet_r50-caffe_ms-1x_coco
    In Collection: TridentNet
    Config: configs/tridentnet/tridentnet_r50-caffe_ms-1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tridentnet/tridentnet_r50_caffe_mstrain_1x_coco/tridentnet_r50_caffe_mstrain_1x_coco_20201230_141839-6ce55ccb.pth

  - Name: tridentnet_r50-caffe_ms-3x_coco
    In Collection: TridentNet
    Config: configs/tridentnet/tridentnet_r50-caffe_ms-3x_coco.py
    Metadata:
      Epochs: 36
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.3
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tridentnet/tridentnet_r50_caffe_mstrain_3x_coco/tridentnet_r50_caffe_mstrain_3x_coco_20201130_100539-46d227ba.pth
