dist: bionic  # ubuntu 18.04
language: python

python:
  - "3.6"
  - "3.7"

env:
  global:
    - CUDA=10.1.105-1
    - CUDA_SHORT=10.1
    - UBUNTU_VERSION=ubuntu1804
    - FORCE_CUDA=1
  matrix:
    - TORCH=1.3.1 TORCHVISION=0.4.2 CUDA_ARCH=6.0
    - TORCH=1.5.0 TORCHVISION=0.6.0 CUDA_ARCH=7.0

cache: pip

# Ref to CUDA installation in Travis: https://github.com/jeremad/cuda-travis
before_install:
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${CUDA_HOME}/include:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - sudo apt-get install -y ninja-build

install:
  - pip install Pillow==6.2.2  # remove this line when torchvision>=0.5
  - pip install torch==${TORCH} torchvision==${TORCHVISION}
  - pip install "git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI"
  - pip install -r requirements.txt

before_script:
  - flake8 .
  - isort -rc --check-only --diff mmdet/ tools/ tests/
  - yapf -r -d --style .style.yapf mmdet/ tools/ tests/ configs/

script:
  - python setup.py check -m -s
  - TORCH_CUDA_ARCH_LIST="${CUDA_ARCH}" python setup.py build_ext --inplace
  - coverage run --branch --source mmdet -m py.test -v --xdoctest-modules tests mmdet

after_success:
  - coverage report -m
