Collections:
  - Name: SSD
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - VGG
    Paper: https://arxiv.org/abs/1512.02325
    README: configs/ssd/README.md

Models:
  - Name: ssd300_coco
    In Collection: SSD
    Config: configs/ssd/ssd300_coco.py
    Metadata:
      Training Memory (GB): 9.9
      inference time (s/im): 0.02288
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 25.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/ssd/ssd300_coco/ssd300_coco_20210604_193052-b61137df.pth

  - Name: ssd512_coco
    In Collection: SSD
    Config: configs/ssd/ssd512_coco.py
    Metadata:
      Training Memory (GB): 19.4
      inference time (s/im): 0.03257
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 29.8
    Weights: https://download.openmmlab.com/mmdetection/v2.0/ssd/ssd512_coco/ssd512_coco_20210604_111835-d3eba047.pth
