# Description.
name: Custom Object Detection ATSS
task_type: DETECTION
task_family: VISION
instantiation: "CLASS"
summary: ATSS with MobileNetV2 backbone.
application:
  ~

# Algo backend.
framework: OTEDetection v2.9.1

# Task implementations.
entrypoints:
  base: mmdet.apis.ote.apis.detection.OTEDetectionTask
  openvino: mmdet.apis.ote.apis.detection.OpenVINODetectionTask

# Hyperparameters.
hyper_parameters:
  base_path: ../../../../mmdet/apis/ote/apis/detection/configuration.yaml
  parameter_overrides:
    learning_parameters:
      batch_size:
        default_value: 8
      learning_rate:
        default_value: 0.009
      learning_rate_warmup_iters:
        default_value: 200

# Training resources.
max_nodes: 1
training_targets:
  - GPU
  - CPU
