Collections:
  - Name: Mask2Former
    Metadata:
      Training Techniques:
        - AdamW
        - Weight Decay
      Training Resources: 8x A100 GPUs
      Architecture:
        - Mask2Former
    Paper:
      URL: https://arxiv.org/pdf/2112.10764.pdf
      Title: Mask2Former for Video Instance Segmentation
    README: configs/mask2former/README.md

Models:
  - Name: mask2former_r50_8xb2-8e_youtubevis2021
    In Collection: Mask2Former
    Config: configs/mask2former_vis/mask2former_r50_8xb2-8e_youtubevis2021.py
    Metadata:
      Training Data: YouTube-VIS 2021
      Training Memory (GB): 6.0
    Results:
      - Task: Video Instance Segmentation
        Dataset: YouTube-VIS 2021
        Metrics:
          AP: 41.3
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mask2former_vis/mask2former_r50_8xb2-8e_youtubevis2021/mask2former_r50_8xb2-8e_youtubevis2021_20230426_131833-5d215283.pth

  - Name: mask2former_r101_8xb2-8e_youtubevis2021
    In Collection: Mask2Former
    Config: configs/mask2former_vis/mask2former_r101_8xb2-8e_youtubevis2021.py
    Metadata:
      Training Data: YouTube-VIS 2021
      Training Memory (GB): 7.5
    Results:
      - Task: Video Instance Segmentation
        Dataset: YouTube-VIS 2021
        Metrics:
          AP: 42.3
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mask2former_vis/mask2former_r101_8xb2-8e_youtubevis2021/mask2former_r101_8xb2-8e_youtubevis2021_20220823_092747-8077d115.pth

  - Name: mask2former_swin-l-p4-w12-384-in21k_8xb2-8e_youtubevis2021.py
    In Collection: Mask2Former
    Config: configs/mask2former_vis/mask2former_swin-l-p4-w12-384-in21k_8xb2-8e_youtubevis2021.py
    Metadata:
      Training Data: YouTube-VIS 2021
      Training Memory (GB): 18.5
    Results:
      - Task: Video Instance Segmentation
        Dataset: YouTube-VIS 2021
        Metrics:
          AP: 52.3
    Weights: https://download.openmmlab.com/mmdetection/v3.0/mask2former_vis/mask2former_swin-l-p4-w12-384-in21k_8xb2-8e_youtubevis2021/mask2former_swin-l-p4-w12-384-in21k_8xb2-8e_youtubevis2021_20220907_124752-48252603.pth
