Collections:
  - Name: Cascade RPN
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - Cascade RPN
        - FPN
        - ResNet
    Paper:
      URL: https://arxiv.org/abs/1909.06720
      Title: 'Cascade RPN: Delving into High-Quality Region Proposal Network with Adaptive Convolution'
    README: configs/cascade_rpn/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.8.0/mmdet/models/dense_heads/cascade_rpn_head.py#L538
      Version: v2.8.0

Models:
  - Name: cascade-rpn_fast-rcnn_r50-caffe_fpn_1x_coco
    In Collection: Cascade RPN
    Config: configs/cascade_rpn/cascade-rpn_fast-rcnn_r50-caffe_fpn_1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/cascade_rpn/crpn_fast_rcnn_r50_caffe_fpn_1x_coco/crpn_fast_rcnn_r50_caffe_fpn_1x_coco-cb486e66.pth

  - Name: cascade-rpn_faster-rcnn_r50-caffe_fpn_1x_coco
    In Collection: Cascade RPN
    Config: configs/cascade_rpn/cascade-rpn_faster-rcnn_r50-caffe_fpn_1x_coco.py
    Metadata:
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/cascade_rpn/crpn_faster_rcnn_r50_caffe_fpn_1x_coco/crpn_faster_rcnn_r50_caffe_fpn_1x_coco-c8283cca.pth
