Collections:
  - Name: RepPoints
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - Group Normalization
        - FPN
        - RepPoints
        - ResNet
    Paper:
      URL: https://arxiv.org/abs/1904.11490
      Title: 'RepPoints: Point Set Representation for Object Detection'
    README: configs/reppoints/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.0.0/mmdet/models/detectors/reppoints_detector.py#L9
      Version: v2.0.0

Models:
  - Name: reppoints-bbox_r50_fpn-gn_head-gn-grid_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-bbox_r50_fpn-gn_head-gn-grid_1x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (ms/im):
        - value: 62.89
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/bbox_r50_grid_fpn_gn-neck%2Bhead_1x_coco/bbox_r50_grid_fpn_gn-neck%2Bhead_1x_coco_20200329_145916-0eedf8d1.pth

  - Name: reppoints-bbox_r50-center_fpn-gn_head-gn-grid_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-bbox_r50-center_fpn-gn_head-gn-grid_1x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (ms/im):
        - value: 64.94
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/bbox_r50_grid_fpn_gn-neck%2Bhead_1x_coco/bbox_r50_grid_fpn_gn-neck%2Bhead_1x_coco_20200329_145916-0eedf8d1.pth

  - Name: reppoints-moment_r50_fpn_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-moment_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 3.3
      inference time (ms/im):
        - value: 54.05
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.0
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_1x_coco/reppoints_moment_r50_fpn_1x_coco_20200330-b73db8d1.pth

  - Name: reppoints-moment_r50_fpn-gn_head-gn_1x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-moment_r50_fpn-gn_head-gn_1x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (ms/im):
        - value: 57.14
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_gn-neck%2Bhead_1x_coco/reppoints_moment_r50_fpn_gn-neck%2Bhead_1x_coco_20200329_145952-3e51b550.pth

  - Name: reppoints-moment_r50_fpn-gn_head-gn_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-moment_r50_fpn-gn_head-gn_2x_coco.py
    Metadata:
      Training Memory (GB): 3.9
      inference time (ms/im):
        - value: 57.14
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r50_fpn_gn-neck%2Bhead_2x_coco/reppoints_moment_r50_fpn_gn-neck%2Bhead_2x_coco_20200329-91babaa2.pth

  - Name: reppoints-moment_r101_fpn-gn_head-gn_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-moment_r101_fpn-gn_head-gn_2x_coco.py
    Metadata:
      Training Memory (GB): 5.8
      inference time (ms/im):
        - value: 72.99
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r101_fpn_gn-neck%2Bhead_2x_coco/reppoints_moment_r101_fpn_gn-neck%2Bhead_2x_coco_20200329-4fbc7310.pth

  - Name: reppoints-moment_r101-dconv-c3-c5_fpn-gn_head-gn_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-moment_r101-dconv-c3-c5_fpn-gn_head-gn_2x_coco.py
    Metadata:
      Training Memory (GB): 5.9
      inference time (ms/im):
        - value: 82.64
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 42.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco/reppoints_moment_r101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco_20200329-3309fbf2.pth

  - Name: reppoints-moment_x101-dconv-c3-c5_fpn-gn_head-gn_2x_coco
    In Collection: RepPoints
    Config: configs/reppoints/reppoints-moment_x101-dconv-c3-c5_fpn-gn_head-gn_2x_coco.py
    Metadata:
      Training Memory (GB): 7.1
      inference time (ms/im):
        - value: 107.53
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.2
    Weights: https://download.openmmlab.com/mmdetection/v2.0/reppoints/reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco/reppoints_moment_x101_fpn_dconv_c3-c5_gn-neck%2Bhead_2x_coco_20200329-f87da1ea.pth
