Collections:
  - Name: YOLOv3
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - DarkNet
    Paper: https://arxiv.org/abs/1804.02767
    README: configs/yolo/README.md

Models:
  - Name: yolov3_d53_320_273e_coco
    In Collection: YOLOv3
    Config: configs/yolo/yolov3_d53_320_273e_coco.py
    Metadata:
      Training Memory (GB): 2.7
      inference time (ms/im):
        - value: 15.65
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (320, 320)
      Epochs: 273
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 27.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_320_273e_coco/yolov3_d53_320_273e_coco-421362b6.pth

  - Name: yolov3_d53_mstrain-416_273e_coco
    In Collection: YOLOv3
    Config: configs/yolo/yolov3_d53_mstrain-416_273e_coco.py
    Metadata:
      Training Memory (GB): 3.8
      inference time (ms/im):
        - value: 16.34
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (416, 416)
      Epochs: 273
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 30.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_mstrain-416_273e_coco/yolov3_d53_mstrain-416_273e_coco-2b60fcd9.pth

  - Name: yolov3_d53_mstrain-608_273e_coco
    In Collection: YOLOv3
    Config: configs/yolo/yolov3_d53_mstrain-608_273e_coco.py
    Metadata:
      Training Memory (GB): 7.4
      inference time (ms/im):
        - value: 20.79
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (608, 608)
      Epochs: 273
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 33.7
    Weights: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_mstrain-608_273e_coco/yolov3_d53_mstrain-608_273e_coco_20210518_115020-a2c3acb8.pth

  - Name: yolov3_d53_fp16_mstrain-608_273e_coco
    In Collection: YOLOv3
    Config: configs/yolo/yolov3_d53_fp16_mstrain-608_273e_coco.py
    Metadata:
      Training Memory (GB): 4.7
      inference time (ms/im):
        - value: 20.79
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP16
          resolution: (608, 608)
      Epochs: 273
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 33.8
    Weights: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_d53_fp16_mstrain-608_273e_coco/yolov3_d53_fp16_mstrain-608_273e_coco_20210517_213542-4bc34944.pth

  - Name: yolov3_mobilenetv2_320_300e_coco
    In Collection: YOLOv3
    Config: configs/yolo/yolov3_mobilenetv2_320_300e_coco.py
    Metadata:
      Training Memory (GB): 3.2
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 22.2
    Weights: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_mobilenetv2_320_300e_coco/yolov3_mobilenetv2_320_300e_coco_20210719_215349-d18dff72.pth

  - Name: yolov3_mobilenetv2_mstrain-416_300e_coco
    In Collection: YOLOv3
    Config: configs/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco.py
    Metadata:
      Training Memory (GB): 5.3
      Epochs: 300
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 23.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/yolo/yolov3_mobilenetv2_mstrain-416_300e_coco/yolov3_mobilenetv2_mstrain-416_300e_coco_20210718_010823-f68a07b3.pth
